### ISSUE TITLE
Does not compile with /SEH

### ISSUE THREAD

**Issue by ByteWhite1x1** [Ido-Moshe-Github/CiDllDemo#6]
Hi. 

Thanks for the effort. The example driver compiles provided /SEH is turned off.

I encountered nothing but horror while trying to get this working in my kernel driver (VS2019 16.11.34
). Various errors such as 

unresolved external symbol __CxxFrameHandler4
unresolved external symbol __GSHandlerCheck_EH4

I found out that if you disable C++ exceptions my driver compiled just fine. SEH exceptions are a must in any kernel driver. However the ApiValidator did not allowed the project to be compiled.

The solution:

typedef NTSTATUS(NTAPI* pCiValidateFileObject)(IN _FILE_OBJECT* fileObject, IN int a2, IN int a3, 
	OUT PolicyInfo* policyInfoForSigner, OUT PolicyInfo* policyInfoForTimestampingAuthority,
	OUT LARGE_INTEGER* signingTime, OUT BYTE* digestBuffer, IN OUT int* digestSize, OUT int* digestIdentifier);

pCiValidateFileObject CiValidateFileObject;

PVOID pCi = GetExportedRoutine((void*)baseAddress, "CiValidateFileObject", NULL);

		if (!pCi)
		{
			return STATUS_UNSUCCESSFUL;
		}

		CiValidateFileObject = (pCiValidateFileObject)pCi;

Here is the output:

00000001	0.00000000	[+] CreateProcess: ParentId: 6372 (explorer.exe) pId: 13396 \??\C:\C#\Console\bin\Debug\net8.0-windows\Console.exe	
00000002	0.00002510	[+] ValidateFileUsingCiValidateFileObject 	
00000003	0.00341210	[+] CiValidateFileObject returned 0xC0000428

"Console.exe" is an unsigned.  Your solution worked on Windows 11 Pro 22H3. Thanks!
